name: "build-dev"
on: [push]

jobs:
  build-dev:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli

      - name: Install Vite
        run: npm install

      - name: Build Vite
        run: npm run build

      # Customize:

      - name: Install Tree
        run: brew install tree

      - name: Build App
        run: yarn tauri build

      - name: Read MacOS Dir
        run: tree

      - name: Copy File
        run: cp src-tauri/target/release/bundle/macos/github-actions-test.app github-actions-test.app

      - name: Release MacOS
        uses: softprops/action-gh-release@v1
        with:
          name: v1.0.0
          body: Download the app and run it
          draft: true
          prerelease: true
          files: |
            github-actions-test.app
