name: "Build Tauri"

on: [push]

jobs:
  build-tauri:
    # needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      # Enter Workspace
      - run: |
          node -v
          npm -v
          npx -v
          java -version
          javac -version
