name: "Build Tauri"

on:
  push:
    tags:
      - "metadata-v*"

jobs:
  build-tauri:
    # needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      # Clone Workspace
      - uses: actions/checkout@v3

      - name: "Print Metadata"
        run: bash metadata/print.sh
